// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb41oWE_GnMuycwWR6fVm-X-kS1WiFVFw',
    appId: '1:778645207750:web:cca2df2bafedfa5066f5c7',
    messagingSenderId: '778645207750',
    projectId: 'chat-app-a5c1a',
    authDomain: 'chat-app-a5c1a.firebaseapp.com',
    storageBucket: 'chat-app-a5c1a.firebasestorage.app',
    measurementId: 'G-BW6CB20M03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8TW5xFWIUKu3yNr8zdzhTU-1lXXJ5mxo',
    appId: '1:778645207750:android:ff5fe0c1f1fc3ed366f5c7',
    messagingSenderId: '778645207750',
    projectId: 'chat-app-a5c1a',
    storageBucket: 'chat-app-a5c1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGuqFeXXivs3cUm2QnOmxW7uapGGiIro',
    appId: '1:778645207750:ios:61e61998ddcfb2d266f5c7',
    messagingSenderId: '778645207750',
    projectId: 'chat-app-a5c1a',
    storageBucket: 'chat-app-a5c1a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGuqFeXXivs3cUm2QnOmxW7uapGGiIro',
    appId: '1:778645207750:ios:61e61998ddcfb2d266f5c7',
    messagingSenderId: '778645207750',
    projectId: 'chat-app-a5c1a',
    storageBucket: 'chat-app-a5c1a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb41oWE_GnMuycwWR6fVm-X-kS1WiFVFw',
    appId: '1:778645207750:web:f240b0f768cad77566f5c7',
    messagingSenderId: '778645207750',
    projectId: 'chat-app-a5c1a',
    authDomain: 'chat-app-a5c1a.firebaseapp.com',
    storageBucket: 'chat-app-a5c1a.firebasestorage.app',
    measurementId: 'G-31MKHH262J',
  );
}
